FROM ubuntu:14.04

MAINTAINER Damian Soriano <ds@ingadhoc.com>

RUN apt-get clean
RUN apt-get update
RUN apt-get upgrade -y

RUN apt-get -y install postgresql

RUN apt-get -y install python
RUN apt-get -y install python-pip

RUN apt-get -y install rsync

RUN apt-get -y install postgresql-server-dev-all

RUN apt-get -y install libpq-dev python-dev

RUN pip install argcomplete
RUN pip install argh
RUN pip install psycopg2
RUN pip install python-dateutil
RUN pip install distribute

RUN apt-get -y install barman

ADD backup_id_rsa.pub /var/lib/postgresql/.ssh/id_rsa.pub
RUN chown -R postgres.postgres /var/lib/postgresql/.ssh

RUN /etc/init.d/ssh start

#RUN service postgresql start

EXPOSE 22

CMD ["/bin/bash"]
